schema_version = "1.0.0"

id = "sme_blender"
version = "0.0.1"
name = "Simple Model Engine"
tagline = "Powerful API to create animations for SME using Blender"

maintainer = "timtaran <Aspirata.minecraft@gmail.com>"
website = "https://clwn.su/"

type = "add-on"

license = ["SPDX:GPL-3.0-or-later"]
platforms = ["windows-x64", "linux-x64"]
tags = ["3D View", "Animation"]
blender_version_min = "4.2.0"

[permissions]
files = "Save scene files"
clipboard = "Save scene data"